name = "news-update"
main = "src/index.js"
compatibility_date = "2024-11-01"

[triggers]
crons = ["0 23,5,11 * * *"] # 06:00, 12:00, 18:00 WIB

[vars]
NIM_MODEL = "nvidia/nemotron-3-super-120b-a12b"
PER_FEED = "5"
PER_CATEGORY = "4"

[[kv_namespaces]]
binding = "SEEN"
id = "0817ebc36ef54604ad74e13d78be2455"
