name: Automasi Bot Berita Telegram

# Menentukan kapan skrip ini akan dijalankan
on:
  schedule:
    # Waktu berjalan menggunakan zona waktu UTC.
    # 08:00 WIB = 01:00 UTC. Format cron: Menit Jam Tanggal Bulan Hari
    - cron: '0 1 * * *' 
  workflow_dispatch: # Fitur sakti agar Anda bisa menjalankan skrip ini secara manual lewat tombol

jobs:
  jalankan-bot:
    runs-on: ubuntu-latest # Menumpang server Linux gratis dari GitHub

    steps:
      - name: Mengambil kode dari repository
        uses: actions/checkout@v3

      - name: Menyiapkan lingkungan Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Menginstal library yang dibutuhkan
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Menjalankan skrip bot_berita.py
        env:
          # Memanggil rahasia yang tadi kita buat di Settings
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
